todo/notes/urls.py
from django.urls import path
from . import views
app_name = "notes"

urlpatterns = [
    path("", views.home_view, name="homepage"),
    path("about/",views.about_view,name="aboutpage"),
    # path("create/",views.todo_create_view,name="create-todo"),
    path("update_todo/<int:pk>/",views.update_todo,name="update-todo"),
    path("delete_todo/<int:pk>/",views.delete_todo,name="delete-todo"),



]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("user.urls")),
    path("login/",auth_views.LoginView.as_view(template_name="user/login.html"),name="login"),
    path("logout/",auth_views.LogoutView.as_view(template_name="user/logout.html"),name="logout"),
    path("",include("notes.urls")),
]

todo/user/urls.py
from django.urls import path,include
from . import views
app_name="user"

urlpatterns = [
    path("register/",views.register_view,name="registerpage"),

]

todo/notes/models.py
from django.db import models

# Create your models here.
class todo(models.Model):
    title=models.CharField(max_length=600)
    # description=models.TextField()
    status=models.BooleanField(default=False)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return self.title

todo/user/models.py
from django.db import models
from django.contrib.auth.models import User

class account(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name

todo/notes/forms.py
from django import forms
from .models import todo

class create_todo(forms.ModelForm):
   title= forms.CharField(widget= forms.TextInput(attrs={'placeholder':'Add new task...'}))
   class Meta:
        model= todo
        fields='__all__'

todo/user/forms.py
from django import forms
from .models import account
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class login_form(forms.Form):
    username=forms.CharField(max_length=100)
    password=forms.CharField(widget=forms.PasswordInput)


class register_form(UserCreationForm):
    email=forms.EmailField()
    
    class meta:
        Model=User
        fields=["username","email", "password1","password2"]

todo/notes/views.py
from django.shortcuts import render,redirect
from .models import todo
from .forms import create_todo
# Create your views here.
def home_view(request):
    todos=todo.objects.all()
    form=create_todo()
    if request.method=="POST":
        form=create_todo(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form=create_todo()
    context={"todos":todos,"form":form}
    return render(request,"notes/home.html",context)

def about_view(request):
    return render(request,"notes/about.html")

# def todo_create_view(request):
#     if request.method=="POST":
#         form=create_todo(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("/")
#     else:
#         form=create_todo()
#     context={"form":form}
#     return render(request,"notes/home.html",context)

def update_todo(request,pk):
    todos=todo.objects.get(id=pk)
    
    form=create_todo(instance=todos)
    if request.method=="POST":
        form=create_todo(request.POST,instance=todos)
        if form.is_valid():
            form.save()
            return redirect("/")
    context={"form":form}
       
    return render(request,"notes/update_todo.html",context)

def delete_todo(request,pk):
    item=todo.objects.get(id=pk)
    if request.method=="POST":
        item.delete()
        return redirect("/")
    context={"item":item}
    return render(request,"notes/delete_todo.html",context)

todo/user/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import register_form,login_form
from django.contrib import messages
# Create your views here.

# def login_view(request):
#     if request.method=="POST":
#         form=login_form(request.POST)
#         if form.is_valid():
#             cd=form.cleaned_data
#             user=authenticate(request,username=cd["username"],password=cd["password"])

#             if user is not None:
#                 if user.is_active:
#                     login(request,user)
#                     return HttpResponse("you have been login")
#                 else:
#                     return HttpResponse("disable account")
#             else:
#                 return HttpResponse("invalid loign")
#     else:
#         form=login_form
#     return render(request,"user/login.html",{"form":form})

def register_view(request):
    form=register_form()
    if request.method=="POST":
        form=register_form(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    
    form=register_form()
    return render(request,"user/register.html",{"form":form})

todo/notes/templates/notes/about.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        
    </style>
    <title>about</title>
  </head>
  <body>
    <!-- <h1>Hello, world!</h1> -->
    <div class="container">
        <div class="row border">
            <div class="col-md-2 border ">about</div>
            <div class="col-md-2"> page</div>
          </div>
      </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

todo/notes/templates/notes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>

	body{
		background-color: #638CB8;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #6BA3E8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}

	.item-row{
		background-color: #906abd;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}

	.btn-danger{
		background-color: #ffae19;
		border-color: #e59400;
	}

.nav-link{
	display: flex;
    flex-direction: row-reverse;
    

}
.nav-item{
	
	color: black;
	gap: 10px;
	padding: 10px 10px 10px;
}

</style>

</head>
<body>
    <div class="nav-link">
        {% if user.is_authenticated %}
        <a class="nav-item" href="{% url 'notes:aboutpage' %}">about </a>
        <a class="nav-item " href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="nav-item" href="{% url 'login' %}">Login</a>
        <a class="nav-item" href="{% url 'user:registerpage' %}">Register</a>
        {% endif %}
		{% block content %}
		
		{% endblock %}
	</div>
    
</body>
</html>

todo/notes/templates/notes/create_todo.html
{% extends "notes/base.html" %}
{% block content %}
    <form  method="post" action="">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="create">
    </form>
    
{% endblock %}

todo/notes/templates/notes/delete_todo.html
{% extends "notes/base.html" %}
{% block content  %}
    <form method="post" action="">
        {% csrf_token %}
        <p>are you sure u want to delete this </p>
        
        <input type="submit" name="delete">
        <a href="{% url 'notes:homepage' %}">cancel</a>

    </form>

    {% endblock %}

todo/notes/templates/notes/home.html
{%extends "notes/base.html" %}
{% block content %}
    

    <div class="center-column">
        <form method="POST" action="/">
            {% csrf_token %}
            {{form.title}}
            <input class="btn btn-info" type="submit" name="Create Task">
        </form>
        <div class="todo-list">
            
        {% for todo in todos %}
        <div class="item-row">

            {% if todo.status ==  True %}
             <strike>{{ todo }}</strike>
            {% else %}
            <span>{{ todo }}</span>
            {% endif %}
            
            <a class="btn btn-sm btn-info" href="{% url 'notes:update-todo' todo.id %}">update</a>
            <a class="btn btn-sm btn-danger" href="{% url 'notes:delete-todo' todo.id %}">delete</a>
        </div>
        
        {% endfor %}
    </div>
    
    {% endblock %}
</div>

todo/notes/templates/notes/update_todo.html
{% extends "notes/base.html" %}
 {% block content %}
    <p>update todo</p>
    <form method="post">

        {% csrf_token %}
        {{form.as_p}}
        
        
        <input type="submit" name="update" >
    </form>
    
{% endblock %}

todo/user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
</head>
<body>
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <p><input type="submit" value="login"></p>
    </form>

    
</body>
</html>

todo/user/templates/user/logout.html
{% block content %}
<h2>You have been logged-out</h2>
<div class="border-top pd-3 ">
    <small class="text-muted">
        <a href="{% url 'login' %}">Log-in again</a>
    </small>

</div>
{% endblock %}

todo/user/templates/user/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>register</title>
</head>

<body>
    <form method="post" action="">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="register">
    </form>
</body>

</html>